# Generated by Django 3.2.15 on 2022-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('location_zip', models.IntegerField()),
                ('location_name', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
