# Generated by Django 3.2.15 on 2022-10-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='auth_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
