# Generated by Django 3.2.15 on 2022-10-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_playlist', '0002_playlist_auth_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist',
            new_name='PlaylistInProgress',
        ),
    ]
