# Generated by Django 3.2.15 on 2022-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_playlist', '0003_rename_playlist_playlistinprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_count', models.IntegerField()),
                ('concert_count', models.IntegerField()),
            ],
        ),
    ]
